// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervacijaSmjestaja.Data;

#nullable disable

namespace RezervacijaSmjestaja.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250203121538_daaa")]
    partial class daaa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RezervacijaSmjestaja.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("RezervacijaSmjestaja.Models.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("SmjestajId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("SmjestajId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("RezervacijaSmjestaja.Models.Smjestaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaPoNoci")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Grad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SlikaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Smjestaji");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CijenaPoNoci = 120m,
                            Grad = "Zagreb",
                            Naziv = "Modern City Apartment",
                            Opis = "Luksuzan apartman u centru grada",
                            SlikaUrl = "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 2,
                            CijenaPoNoci = 250m,
                            Grad = "Split",
                            Naziv = "Seaside Apartment",
                            Opis = "Apartman s pogledom na more",
                            SlikaUrl = "https://images.pexels.com/photos/3075991/pexels-photo-3075991.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 3,
                            CijenaPoNoci = 180m,
                            Grad = "Rijeka",
                            Naziv = "Cozy Mountain Loft",
                            Opis = "Moderan loft u planinama",
                            SlikaUrl = "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 4,
                            CijenaPoNoci = 300m,
                            Grad = "Osijek",
                            Naziv = "Luxury Penthouse",
                            Opis = "Ekskluzivan penthouse s terasom",
                            SlikaUrl = "https://images.pexels.com/photos/1757413/pexels-photo-1757413.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 5,
                            CijenaPoNoci = 100m,
                            Grad = "Dubrovnik",
                            Naziv = "Rustic Countryside Home",
                            Opis = "Udobna kuća u prirodi",
                            SlikaUrl = "https://images.pexels.com/photos/751268/pexels-photo-751268.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 6,
                            CijenaPoNoci = 200m,
                            Grad = "Pula",
                            Naziv = "Tropical Beach Apartment",
                            Opis = "Apartman uz samu plažu",
                            SlikaUrl = "https://images.pexels.com/photos/221457/pexels-photo-221457.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 7,
                            CijenaPoNoci = 160m,
                            Grad = "Zadar",
                            Naziv = "Elegant City Suite",
                            Opis = "Moderan apartman s elegantnim dizajnom",
                            SlikaUrl = "https://images.pexels.com/photos/813691/pexels-photo-813691.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 8,
                            CijenaPoNoci = 220m,
                            Grad = "Šibenik",
                            Naziv = "Hillside Retreat",
                            Opis = "Apartman na osami s predivnim pogledom",
                            SlikaUrl = "https://images.pexels.com/photos/2102437/pexels-photo-2102437.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 9,
                            CijenaPoNoci = 140m,
                            Grad = "Varaždin",
                            Naziv = "Panoramic View Apartment",
                            Opis = "Apartman s panoramskim pogledom",
                            SlikaUrl = "https://images.pexels.com/photos/276528/pexels-photo-276528.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 10,
                            CijenaPoNoci = 320m,
                            Grad = "Karlovac",
                            Naziv = "Seaview Penthouse",
                            Opis = "Penthouse s pogledom na more",
                            SlikaUrl = "https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 11,
                            CijenaPoNoci = 110m,
                            Grad = "Makarska",
                            Naziv = "Downtown Studio",
                            Opis = "Minimalistički studio u centru",
                            SlikaUrl = "https://images.pexels.com/photos/374689/pexels-photo-374689.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 12,
                            CijenaPoNoci = 130m,
                            Grad = "Hvar",
                            Naziv = "Wooden Chalet",
                            Opis = "Planinska brvnara za potpuni odmor",
                            SlikaUrl = "https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 13,
                            CijenaPoNoci = 400m,
                            Grad = "Zadar",
                            Naziv = "Luxury Villa",
                            Opis = "Privatna vila s bazenom",
                            SlikaUrl = "https://images.pexels.com/photos/2103999/pexels-photo-2103999.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 14,
                            CijenaPoNoci = 175m,
                            Grad = "Šibenik",
                            Naziv = "Modern Apartment",
                            Opis = "Stilno uređen apartman u centru",
                            SlikaUrl = "https://images.pexels.com/photos/262048/pexels-photo-262048.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 15,
                            CijenaPoNoci = 145m,
                            Grad = "Plitvice",
                            Naziv = "Open Space Loft",
                            Opis = "Prostrani loft s modernim dizajnom",
                            SlikaUrl = "https://images.pexels.com/photos/2251247/pexels-photo-2251247.jpeg?w=1280"
                        },
                        new
                        {
                            Id = 16,
                            CijenaPoNoci = 135m,
                            Grad = "Dubrovnik",
                            Naziv = "City Center Apartment",
                            Opis = "Savršeno mjesto za urbane nomade",
                            SlikaUrl = "https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?w=1280"
                        });
                });

            modelBuilder.Entity("RezervacijaSmjestaja.Models.Rezervacija", b =>
                {
                    b.HasOne("RezervacijaSmjestaja.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RezervacijaSmjestaja.Models.Smjestaj", "Smjestaj")
                        .WithMany()
                        .HasForeignKey("SmjestajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Smjestaj");
                });
#pragma warning restore 612, 618
        }
    }
}
