// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RezervacijaSmjestaja.Data;

#nullable disable

namespace RezervacijaSmjestaja.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250201173324_ses")]
    partial class ses
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RezervacijaSmjestaja.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("RezervacijaSmjestaja.Models.Rezervacija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<int>("SmjestajId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("SmjestajId");

                    b.ToTable("Rezervacije");
                });

            modelBuilder.Entity("RezervacijaSmjestaja.Models.Smjestaj", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CijenaPoNoci")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SlikaUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Smjestaji");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CijenaPoNoci = 120.00m,
                            Naziv = "Vila Aurora",
                            Opis = "Split, Hrvatska",
                            SlikaUrl = "https://via.placeholder.com/400x200.png?text=Vila+Aurora"
                        },
                        new
                        {
                            Id = 2,
                            CijenaPoNoci = 150.00m,
                            Naziv = "Apartmani Sunce",
                            Opis = "Dubrovnik, Hrvatska",
                            SlikaUrl = "https://via.placeholder.com/400x200.png?text=Apartmani+Sunce"
                        },
                        new
                        {
                            Id = 3,
                            CijenaPoNoci = 100.00m,
                            Naziv = "Bungalovi More",
                            Opis = "Zadar, Hrvatska",
                            SlikaUrl = "https://via.placeholder.com/400x200.png?text=Bungalovi+More"
                        },
                        new
                        {
                            Id = 4,
                            CijenaPoNoci = 200.00m,
                            Naziv = "Hotel Lav",
                            Opis = "Rijeka, Hrvatska",
                            SlikaUrl = "https://via.placeholder.com/400x200.png?text=Hotel+Lav"
                        },
                        new
                        {
                            Id = 5,
                            CijenaPoNoci = 180.00m,
                            Naziv = "Vila Mediteran",
                            Opis = "Šibenik, Hrvatska",
                            SlikaUrl = "https://via.placeholder.com/400x200.png?text=Vila+Mediteran"
                        },
                        new
                        {
                            Id = 6,
                            CijenaPoNoci = 90.00m,
                            Naziv = "Apartmani Mir",
                            Opis = "Pula, Hrvatska",
                            SlikaUrl = "https://via.placeholder.com/400x200.png?text=Apartmani+Mir"
                        });
                });

            modelBuilder.Entity("RezervacijaSmjestaja.Models.Rezervacija", b =>
                {
                    b.HasOne("RezervacijaSmjestaja.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RezervacijaSmjestaja.Models.Smjestaj", "Smjestaj")
                        .WithMany()
                        .HasForeignKey("SmjestajId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Korisnik");

                    b.Navigation("Smjestaj");
                });
#pragma warning restore 612, 618
        }
    }
}
